// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABqWqzCQHUmrQa1YQe7FvyOAm63BnpbBA',
    appId: '1:109956443084:web:27e4397a0dde08c6b80b69',
    messagingSenderId: '109956443084',
    projectId: 'restaurant-order-system-ee49e',
    authDomain: 'restaurant-order-system-ee49e.firebaseapp.com',
    storageBucket: 'restaurant-order-system-ee49e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2DC_I9vgUO556mwyMY5zv82iI6j0RXw',
    appId: '1:109956443084:android:e776e180bfd57a27b80b69',
    messagingSenderId: '109956443084',
    projectId: 'restaurant-order-system-ee49e',
    storageBucket: 'restaurant-order-system-ee49e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIN6seJNlMcxcgD0NFz6PM46RzAv6tQsM',
    appId: '1:109956443084:ios:c1fc4d7928bd4384b80b69',
    messagingSenderId: '109956443084',
    projectId: 'restaurant-order-system-ee49e',
    storageBucket: 'restaurant-order-system-ee49e.firebasestorage.app',
    iosBundleId: 'com.example.staffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIN6seJNlMcxcgD0NFz6PM46RzAv6tQsM',
    appId: '1:109956443084:ios:c1fc4d7928bd4384b80b69',
    messagingSenderId: '109956443084',
    projectId: 'restaurant-order-system-ee49e',
    storageBucket: 'restaurant-order-system-ee49e.firebasestorage.app',
    iosBundleId: 'com.example.staffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABqWqzCQHUmrQa1YQe7FvyOAm63BnpbBA',
    appId: '1:109956443084:web:19feac15a436826cb80b69',
    messagingSenderId: '109956443084',
    projectId: 'restaurant-order-system-ee49e',
    authDomain: 'restaurant-order-system-ee49e.firebaseapp.com',
    storageBucket: 'restaurant-order-system-ee49e.firebasestorage.app',
  );
}
